// Mantener sincronizada con la política autoritativa del backend.
const MANUAL_APPROVAL_SUBCATEGORY_NAMES = new Set([
  "otros",
  "palo de hockey",
  "bates de beisbol",
  "carpas",
  "sillas plegables",
  "cochecitos",
  "paraguas de paseo",
  "huevitos",
  "butacas para auto",
  "computadoras de escritorio",
  "pc gamer",
  "all in one",
  "monitores",
  "soportes para monitor",
  "cpu",
  "gabinetes gamer",
  "sillas gamer",
  "placas madre",
  "gabinetes",
  "coolers",
  "impresoras",
  "impresoras termicas",
  "camas y cuchas",
  "rascadores",
  "areneros",
  "jaulas",
  "casas y refugios",
  "peceras y acuarios",
  "cortadoras de cesped",
  "piedras decorativas",
  "cercos decorativos",
  "bordeadoras",
  "invernaderos domesticos",
  "mesas de jardin",
  "sillas de jardin",
  "sombrillas",
  "hamacas",
  "decoracion exterior",
  "caballetes",
  "tableros de dibujo",
  "cestos de basura",
  "contenedores",
  "separadores para reciclaje",
  "dispensers",
  "equipos para fiestas",
  "tuneles",
  "colchonetas",
  "comederos automaticos",
  "trenes",
  "pistas de autos",
  "casas de munecas",
  "cocinitas",
  "monopatines",
  "patinetas",
  "piscinas inflables",
  "plantas de interior",
  "plantas de exterior",
  "plantas aromaticas",
  "cactus",
  "bonsais",
  "flores",
  "jardineras",
  "portamacetas",
  "composteras",
  "kits de huerta",
  "bancales",
  "sustrato para huerta",
  "sustrato universal",
  "tierra",
  "turba",
  "compost",
  "perlita",
  "sistemas de riego",
  "espejos",
  "relojes de pared",
  "percheros",
  "estantes",
  "zapateros",
  "valijas",
  "bancos de musculacion",
  "estaciones multifuncion",
  "home gym",
  "cintas para correr",
  "bicicletas fijas",
  "bicicletas de spinning",
  "elipticos",
  "escaladores",
  "maquinas de remo",
  "sacos de boxeo",
  "cajas pliometricas",
  "maquinas de piernas",
  "maquinas de pecho",
  "poleas",
  "prensas",
  "mobiliario gamer",
  "escritorios",
  "pantallas verdes",
  "maquinas arcade",
  "alfombras grandes",
]);

function normalizePolicyName(name: string) {
  return name
    .trim()
    .toLocaleLowerCase("es-AR")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function subCategoryRequiresManualApproval(name: string) {
  return MANUAL_APPROVAL_SUBCATEGORY_NAMES.has(normalizePolicyName(name));
}
